spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 512MB

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      smtp:
        auth: ${SMTP_AUTH_ENABLED}
        starttls:
          enable: ${SMTP_STARTTLS_ENABLED}

logging:
  level:
    root: info
    org.springframework: info
    be.zsoft.zscore.core: debug

zscore:
  cors:
    allowed-origins: ${ZSCORE_CORS_ALLOWED_ORIGINS}
  security:
    token:
      secret: ${ZSCORE_TOKEN_SECRET}
      token-expiry-duration: ${ZSCORE_TOKEN_EXPIRY_DURATION}
      refresh-token-expiry-duration: ${ZSCORE_REFRESH_TOKEN_EXPIRY_DURATION}
      player-token-expiry-duration: ${ZSCORE_PLAYER_TOKEN_EXPIRY_DURATION}
      player-refresh-token-expiry-duration: ${ZSCORE_PLAYER_REFRESH_TOKEN_EXPIRY_DURATION}
  email:
    override-classpath-templates: ${ZSCORE_EMAIL_OVERRIDE_TEMPLATES:false}
    absolute-email-templates-path: ${ZSCORE_EMAIL_TEMPLATES_PATH:''}
    no-reply-email: ${ZSCORE_EMAIL_NO_REPLY}
    no-reply-name: ${ZSCORE_EMAIL_NO_REPLY_NAME}
    activation-frontend-url: ${ZSCORE_EMAIL_ACTIVATION_URL}
    reset-password-frontend-url: ${ZSCORE_EMAIL_RESET_PASSWORD_URL}
    register-frontend-url: ${ZSCORE_EMAIL_REGISTER_URL}
