name: Build & Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java for building
        uses: actions/setup-java@v3
        with:
          java-version: 24
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package