name: Publish to Docker Hub

# Will run after a git tag has been created
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Retrieve artifact
        uses: actions/download-artifact@v4
        with:
          name: zscore_core-api
          path: target/zscore-core.jar

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: zsoftbe/z-score-core-api:latest,zsoftbe/z-score-core-api:${{ github.ref }}